### ISSUE TITLE
Is PFC154 really supported?

### ISSUE THREAD

**Issue by spth** [cpldcpu/SimPad#1]
The README claims support for the PFC154.

But AFAIK, this device, unlike the similar PFS154, is not yet available; the datasheet was released just yesterday.

If you have a source for the PFC154, it could be useful to also add support for this device to the easy-pdk-programmer (https://github.com/free-pdk/easy-pdk-programmer-software/issues/8).

**Comment by cpldcpu** [comment]
That was a typo. I was actually the PMS154C. Padauk surely does have confusing component names...
