### ISSUE TITLE
Unclear assemble instructions

### ISSUE THREAD

**Issue by Kashouryo** [cpldcpu/SimPad#2]
This is a really cool project, it's really exciting to see a padauk programmer made out of an Arduino!

However, the instruction at https://github.com/cpldcpu/SimPad/blob/master/Hardware/Readme.md is not really clear. It will be nice to add some additional information on pins(e.g. the digital/analogue pin number on Arduino and the pin number on padauk chip instead of only showing the pin name).
![image](https://user-images.githubusercontent.com/37679684/75188296-e3733a80-5719-11ea-8c11-69d6592b5433.png)

Btw, I am your super fan! I read every article on your blog and your candle reverse engineering article really amazed me.

**Comment by cpldcpu** [comment]
Hi,

thanks a lot for your interest and praise. Sorry for not seeing this earlier.

Unfortunately the programmer can only be seen as half-baked and was never really finished. I would suggest to use the easypdkprog: https://free-pdk.github.io/
